apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-oracle
spec:
  selector:
    matchLabels:
      app: adminer-oracle
  template:
    metadata:
      labels:
        app: adminer-oracle
    spec:
      containers:
        - name: adminer-oracle
          image: mdehnavi/adminer-oracle:4.7.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-oracle-svc
spec:
  selector:
    app: adminer-oracle
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: adminer-oracle
  name: adminer-oracle
spec:
  rules:
    - host: oracle.example.com
      http:
        paths:
          - backend:
              service:
                name: adminer-oracle-svc
                port:
                  number: 8080
            path: /
            pathType: Prefix